### ISSUE TITLE
guru.springfamework.services.CategoryServiceImpl required a bean of type 'guru.springfamework.api.v1.mapper.CategoryMapper' that could not be found

### ISSUE THREAD

**Issue by ryan-learning-git** [springframeworkguru/spring5-mvc-rest#1]
Using only the code in this repo:
`2017-11-15 14:29:02.435  INFO 27523 --- [  restartedMain] utoConfigurationReportLoggingInitializer : 
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-11-15 14:29:02.583 ERROR 27523 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of constructor in guru.springfamework.services.CategoryServiceImpl required a bean of type 'guru.springfamework.api.v1.mapper.CategoryMapper' that could not be found.
Action:
Consider defining a bean of type 'guru.springfamework.api.v1.mapper.CategoryMapper' in your configuration.
Process finished with exit code 0`

This is in IntelliJ, on Linux Mint, Java 8. Any thoughts?

**Comment by springframeworkguru** [comment]
Please submit questions via the course forums. Thanks!
