### ISSUE TITLE
Branch: Category Controller APPLICATION FAILED TO START Issue while upgrading to Spring Boot 2.0.0.M7

### ISSUE THREAD

**Issue by ximanta** [springframeworkguru/spring5-mvc-rest#3]
Starting from Branch: Category Controller, application stops with error:

***************************
APPLICATION FAILED TO START
***************************
Description:

Parameter 0 of constructor in guru.springfamework.services.CategoryServiceImpl required a bean of type 'guru.springfamework.api.v1.mapper.CategoryMapper' that could not be found.

Action:
Consider defining a bean of type 'guru.springfamework.api.v1.mapper.CategoryMapper' in your configuration.

Fixed by upgrading to MapStruct 1.2.0.Final

**Comment by springframeworkguru** [comment]
Problem with IntelliJ and how annotations are processed. Added annotation processor per [Mapstruct](http://mapstruct.org/documentation/ide-support/).

Might still fail. **Run** mvn package if it does fail. 

After running mvn clean, the error will repeat again. (until you run mvn package again)

This is a known defect in IntelliJ see [this link](https://youtrack.jetbrains.com/issue/IDEA-150621).
